name: huy7test
on:
  pull_request:
    type: [opened,reopened,synchronize,labeled,unlabled]
  workflow_dispatch:
jobs:
  test-zui:
    runs-on: ubuntu-latest
    steps:
      - run: echo $PWD
      - run: ls -la
      - run: printenv
      - name: Config aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 ls
      - name: install docker
        run: |
          sudo apt-get update
          sudo apt-get install \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker build 
        run: |
          docker build -t huy7test .
          docker images
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d0c1s4l6
          docker tag huy7test:latest public.ecr.aws/d0c1s4l6/huy7test:latest
          docker push public.ecr.aws/d0c1s4l6/huy7test:latest





