name: huy7test
on:
  push:
    branches: [test]
  pull_request:
    type: [opened,reopened,synchronize,labeled,unlabled]
  workflow_dispatch:
jobs:
  test-zui:
    runs-on: ubuntu-latest
    steps:
      - run: echo $PWD
      - run: ls -la
      - run: printenv
      - name: Config aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 ls
      - name: install docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io
