name: huy7test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  test-zui:
    runs-on: ubuntu-latest
    steps:
      - run: echo "NAME=nguyen cuu duc huy" >> $GITHUB_ENV
      - run: echo "xin chao $NAME"
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo "today is $TODAY"
